correct read_csv header handling
intel-ai/modin pull request #108
Opened 2020-09-08 17:07 UTC by amyskov

This PR corrects header handling by read_csv function for enabling read_csv part in the Census benchmark.

2020-09-09 10:53 UTC, ienkovich requested changes

2020-09-09 10:53 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +import csv
This import is unused and causes falke8 failure

2020-09-09 10:53 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/io.py
> +            elif skiprows is not None and skiprows > 0:
No need to check `skiprows` for `None` in both conditions.

2020-09-09 10:53 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/io.py
> +                skiprows = skiprows if skiprows is not None and skiprows > 2 else 1
How comes `header` parameter is not used here? With passed `names` and `header=0` we have to skip the first row, but with `header=None` we don't need to skip any.

2020-09-09 10:53 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +    @pytest.mark.parametrize("skiprows", [None, 0, 1])
Branch `skiprows > 2` is not tested with these params

2020-09-09 10:53 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +                marks=pytest.mark.xfail(
Would this check that **both** Pandas and Modin `read_csv` methods raise the same error?

2020-09-09 10:53 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +        pandas_df = mpd.read_csv(unique_filename, **kwargs)
You use Modin lib instead of Pandas

2020-09-09 10:53 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +        pandas_df = mpd.read_csv(Path(unique_filename), **kwargs)
You use Modin lib instead of Pandas

2020-09-09 10:53 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +def make_csv_file(
If you need to re-use this function then better move it to test utils, don't make a copy here.

2020-09-11 11:17 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +import csv
Unused import was removed.

2020-09-11 11:19 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/io.py
> +            elif skiprows is not None and skiprows > 0:
Ok, there is only one check in the new commit.

2020-09-11 11:20 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/io.py
> +                skiprows = skiprows if skiprows is not None and skiprows > 2 else 1
Corrected, header parameter is added.

2020-09-11 11:22 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +    @pytest.mark.parametrize("skiprows", [None, 0, 1])
`read_csv` implementation was corrected to cover only Census benchmark case, so this branch was removed.

2020-09-11 11:25 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +                marks=pytest.mark.xfail(
Errors checks are not tested for now, the will be added in the new PRs.

2020-09-11 11:25 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +        pandas_df = mpd.read_csv(unique_filename, **kwargs)
Right, corrected in the new commit.

2020-09-11 11:26 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +        pandas_df = mpd.read_csv(Path(unique_filename), **kwargs)
Corrected.

2020-09-11 11:26 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +def make_csv_file(
Function was removed to the `utils` module.

2020-09-11 11:31 UTC, amyskov commented
@ienkovich thanks for comments, i hope that they were addressed. Note, that In the new commit function implementation was simplified to cover only Census benchmark case.

2020-09-11 15:03 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +from modin.pandas.test.utils import (  # noqa: F401
What is it for? We already have some exceptions in `setup.cfg` for this file.

2020-09-11 15:03 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +    def test_from_csv(self, make_csv_file, header, names):  # noqa: F811
Why is `make_csv_file` a parameter?

2020-09-12 13:09 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/io.py
> +                    raise NotImplementedError(
Ok, `NotImplementedInOmnisciOnRayIO` exception is added and cached in the `except` block.

2020-09-12 13:11 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +                1,
Right. test case with `header==1` is removed and explicit `engine` parameter passing is added.

2020-09-12 13:13 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +        pandas_df = pd.read_csv(Path(unique_filename), **kwargs)
Right, additional runs are not necessary in this case, so they were removed.

2020-09-12 13:14 UTC, amyskov commented on modin/pandas/test/utils.py
> +def make_csv_file(
Ok, single version of `make_csv_function` was left in `modin.pandas.test.test_io` module.

2020-09-12 13:21 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +from modin.pandas.test.utils import (  # noqa: F401
Additional `noqa` comments are needed because pytest fixture imported outside of file it is used (https://stackoverflow.com/questions/47196947/py-test-deal-with-both-pylint-and-flake8-when-importing-features-from-a-module), but it is temporary issue, i think, because after merging these changes into modin master, they should be located in the `modin.pandas.test.test_io` (location of `make_csv_file` pytest fixture). What do you think about it?

2020-09-12 13:23 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +    def test_from_csv(self, make_csv_file, header, names):  # noqa: F811
`make_csv_file` was passed as parameter since this function is a pytest fixture.

2020-09-14 14:55 UTC, ienkovich requested changes

2020-09-14 14:55 UTC, ienkovich commented on modin/pandas/test/test_io.py
> +@pytest.mark.xfail(
Did you break the test?

2020-09-14 14:55 UTC, ienkovich commented on modin/pandas/test/test_io.py
> +            dates = pd.date_range("2000", freq="h", periods=row_size)
Why do you switch to Modin here? Looks like an unrelated change. Overall changes in this file seem unnecessary. We try to keep as small number of changes outside of 'experimental' dir as possible to simplify engine upstreaming.

2020-09-14 14:55 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/io.py
> +class NotImplementedInOmnisciOnRayIO(NotImplementedError):
No need for a new class. NotImplementedError would work just fine. We already use it to fallback to Pandas.

2020-09-14 14:55 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/io.py
> +                    skiprows = skiprows + 1 if skiprows is not None else 1
We need to skip a header when column names are provided only.

2020-09-14 15:05 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +from modin.pandas.test.utils import (  # noqa: F401
I believe we still will have separate tests since we use pyarrow for parsing and we will not be fully compatible with Pandas (e.g. this patch already introduces such incompatibility). In my opinion, reading from the example file like other tests would be a simpler option here.

2020-09-14 17:20 UTC, amyskov commented on modin/pandas/test/utils.py
> +TEST_CSV_FILENAME = "test.csv"
Right, removed in the new commit.

2020-09-14 17:24 UTC, amyskov commented on modin/pandas/test/test_io.py
> +@pytest.mark.xfail(
Test broke when index was removed from .csv file. In order to avoid issues with upstreaming, index was added back to .csv file, so now test is not broken.

2020-09-14 17:26 UTC, amyskov commented on modin/pandas/test/test_io.py
> +            dates = pd.date_range("2000", freq="h", periods=row_size)
Ok, i see, all unrelated changes was removed from PR to simplify engine upstreaming.

2020-09-14 17:27 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/io.py
> +class NotImplementedInOmnisciOnRayIO(NotImplementedError):
Ok, clear. `NotImplementedError` exception is used in the last commit.

2020-09-14 19:36 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/io.py
> +                    skiprows = skiprows + 1 if skiprows is not None else 1
In pyarrow we cannot provide column names and read the header at the same time and therefore we use `skiprows` instead. But if column names are not passed and `header` value is `'infer'` or `0` then we should read it, not skip. Overall:
```
if column names are provided:
  if header == 0:
    skip it
  elif header is None or header == 'infer'
    do nothing
  else:
    fallback to pandas
else:
  if header == 0 or header == 'infer':
    parse it
  elif header is None
     autogenerate names (?)
  else:
    fallback to pandas
```

2020-09-15 12:19 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +from modin.pandas.test.utils import (  # noqa: F401
Ok, is see, file with test data is added in `modin.pandas.test.data`.

2020-09-15 12:28 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/io.py
> +                    skiprows = skiprows + 1 if skiprows is not None else 1
Ok, this scheme was implemented with several changes:
1) In the case when columns names are not provided and `header==0 header=="infer"` no additional parsing is added since it doesn`t needed, reproducer:
```
from pyarrow.csv import read_csv, ParseOptions, ConvertOptions, ReadOptions
import pandas
from modin.pandas.test.utils import df_equals
    
csv_file = "modin/pandas/test/data/read_csv_test_data.csv"
pandas_df = pandas.read_csv(csv_file, header=0)

ro = ReadOptions(
    use_threads=True,
    block_size=None,
    skip_rows=None,
    column_names=None,
    autogenerate_column_names=None,
)
at = read_csv(
    csv_file,
    read_options=ro,
)

modin_df = at.to_pandas()
print(pandas_df)
print(modin_df)

df_equals(modin_df, pandas_df)
```
2) Case when columns names are not provided and `header is None` is falling back to Pandas - i am planning to separate this case to another PR.

2020-09-15 12:51 UTC, ienkovich reviewed
Thanks! This version looks good! Just a couple of minor comments.

2020-09-15 12:51 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +            self.root, "modin/pandas/test/data", "read_csv_test_data.csv"
The new CSV file gives nothing useful to us because this test is for the header and the rest of the data doesn't matter much. We can use some other file, e.g. `test_usecols.csv` with `["a", "b", "c", "d", "e"]` columns list. Let's add new files when we need to cover some new cases.

2020-09-15 12:51 UTC, ienkovich commented on modin/pandas/test/test_io.py
> -
Please avoid this unrelated change.

2020-09-17 09:40 UTC, amyskov commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +            self.root, "modin/pandas/test/data", "read_csv_test_data.csv"
Ok, i see, test data from `test_usecols.csv` is used.

2020-09-17 09:41 UTC, amyskov commented on modin/pandas/test/test_io.py
> -
Ok, unrelated changes are removed.

2020-09-20 13:05 UTC, ienkovich approved these changes

2020-09-20 13:05 UTC, merged