Fix incorrect serialization of various calcite statements
intel-ai/modin pull request #54
Opened 2020-06-24 13:13 UTC by fexolm

## What do these changes do?

- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #? 
- [ ] tests added and passing

2020-06-24 13:35 UTC, ienkovich commented
With this patch tests fail with current OmniSci server. If Calcite server requires different format, then we should either fix servers to consume the same format or support both dialects in Modin at least for a while.

2020-06-25 10:52 UTC, fexolm commented
@ienkovich the only breaking change, for now, is how we deal with aggregate functions. If I wouldn't find other cases, where the server requires a different formats, it shouldn't be hard, to implement conversion on the server side, so we wouldn't need to support different formats.

2020-07-29 13:35 UTC, fexolm commented
@ienkovich @Garra1980 It looks I've done with that changes. PTAL. We also would need to implement mechanism to switch between calcite and non-calcite execution, while using `execute calcite` and `execute relalg` prefixes.

2020-07-29 13:45 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +        "c": [50.0, 40.0, 30.1, 20.0, 10.0],
Why did you have to change it?

2020-07-29 13:46 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/frame/partition_manager.py
> +        at = at.rename_columns(["F_" + str(c) for c in columns])
Since this is a workaround, please make an issue and put a comment here referencing it.

2020-07-29 13:51 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py
> +                "type_precision": 19,
How does test_insert work with this change? It inserts integer literals of various sizes as new columns.

2020-07-29 14:32 UTC, fexolm commented on modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
> +        "c": [50.0, 40.0, 30.1, 20.0, 10.0],
just to check if it works well even with non-integral values

2020-07-29 14:37 UTC, fexolm commented on modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py
> +                "type_precision": 19,
I'm not sure how, but it does work. I'll check out if it works with non-constant precision. I don't really remember why I did this change.

2020-07-29 15:02 UTC, fexolm commented
I fixed most of the comments, however, let's wait before the release is done. Also, I would need to properly rebase the branch.

2020-09-01 14:12 UTC, ienkovich commented on modin/pandas/test/utils.py
> +        assert False, "df1.type != df2.type"
If you want to add an informative message, then better print type names. Also, common changes not related to the OmniSci engine should go directly to the master branch.

2020-09-01 14:14 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/frame/partition_manager.py
> +        if environ.get('MODIN_USE_CALCITE') is not None:
MODIN_USE_CALCITE="False" would lead to Calcite usage which is non-intuitive.

2020-09-01 14:23 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py
> +                "target_type": "BIGINT",
Why do we always use `BIGINT`? For SQL request `"SELECT CAST(1 as SMALLINT) from t1;"` Calcite produces
```
    {
      "id": "1",
      "relOp": "LogicalProject",
      "fields": [
        "EXPR$0"
      ],
      "exprs": [
        {
          "literal": 1,
          "type": "DECIMAL",
          "target_type": "SMALLINT",
          "scale": 0,
          "precision": 1,
          "type_scale": 0,
          "type_precision": 5
        }
      ]
    }
```

2020-09-01 16:58 UTC, fexolm commented on modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py
> +                "target_type": "BIGINT",
Because it just works. I'm not sure what is the correct approach there, BTW.

2020-09-01 17:21 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py
> +                "target_type": "BIGINT",
Here is an example:
```
df = pd.DataFrame({"a" : [1, 2, 3]})
df["b"] = np.int8(1)
print(df["b"])
```
Current result:
```
0    1
1    1
2    1
Name: b, dtype: int8
```
With your changes applied:
```
0    1
1    1
2    1
Name: b, dtype: int64
```
Looks like our DataFrame comparison in tests ignores such difference. But I don't see why we need to lose exact literal types.

2020-09-01 19:49 UTC, ienkovich requested changes

2020-09-01 19:49 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/frame/partition_manager.py
> +
Please use black for formatting

2020-09-01 19:49 UTC, ienkovich commented on modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py
> +                "target_type": "BIGINT",
If we don't have a good reason for that change, it should be removed

2020-09-02 14:19 UTC, ienkovich commented
black and flake8 checks are still failing

2020-09-03 09:03 UTC, fexolm commented
@ienkovich they fail somewhere outside my changes. I don't think fixing them is in the scope of that pr.

2020-09-03 09:17 UTC, ienkovich approved these changes

2020-09-04 07:57 UTC, merged